version: "3.4"

services:
    paper:
        image: build-tools:dev
        build:
            context: .
            target: build-tools
        command: 
            - |
                ~/.please/plz build --show_all_output :paper_pdf
        environment:
            CI_JOB_TOKEN: "${CI_JOB_TOKEN:-}"
            DATASET_PASSWORD: "${DATASET_PASSWORD:-}"
            TEX_OUTPUT_DIR: "."
            KNITR_DRAFT_MODE: "${KNITR_DRAFT_MODE:-TRUE}"
        volumes:
            - "${BUILD_DIR:-.}:/paper"
            - "./cache:/knitr_cache"
            - "${DATA_FETCH_COMMAND:-./data/fetch-dev-data.sh}:/paper/data/fetch-data.sh"
            - "./data/ct rsv time series.csv:/paper/data/rsv.csv" # This is only present for local build
