include: 
  - local: build/docker/bootstrap.yml

stages:
  - digitalocean.pre
  - docker.pre
  - knitr
  - tex
  - digitalocean.post
  
variables:
  DO_DROPLET_PREFIX: gitlab-rsv-ct-optimization
  TEX_DIR: "Paper"
  TEX_OUTPUT_DIR: "Paper/build"
  KNITR_CACHE_DIR: "Paper/build/cache/knitr"

knitr:
  stage: knitr
  tags:
    - docker+private
  image: registry.gitlab.com/airbornemint/rsv-ct-optimization/commit/default:rev-${CI_COMMIT_SHORT_SHA}
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "${KNITR_CACHE_DIR}"
      - "${TEX_DIR}/cache"
  script:
    - git lfs pull
    - printenv DATASET_PASSWORD | gpg --batch --passphrase-fd 0 -o "ct rsv time series.csv" --decrypt "ct rsv time series.csv.gpg"
    - cd "${CI_PROJECT_DIR}/${TEX_DIR}"
    - Rscript -e "knitr::opts_chunk\$set(cache.path='${CI_PROJECT_DIR}/${KNITR_CACHE_DIR}'); knitr::knit('RSVOptimization.rnw')"
    - find .
  artifacts:
    paths:
      - "${TEX_DIR}/RSVOptimization.tex"

tex:
  stage: tex
  tags:
    - docker+private
  image: registry.gitlab.com/airbornemint/rsv-ct-optimization/commit/default:rev-${CI_COMMIT_SHORT_SHA}
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "${KNITR_CACHE_DIR}"
      - "${TEX_DIR}/cache"
  script:
    - cd "${CI_PROJECT_DIR}/${TEX_DIR}"
    - mkdir -p "${CI_PROJECT_DIR}/${TEX_OUTPUT_DIR}"
    - pdflatex -output-dir="${CI_PROJECT_DIR}/${TEX_OUTPUT_DIR}" RSVOptimization.tex
    - cd "${CI_PROJECT_DIR}/${TEX_OUTPUT_DIR}"
    - biblatex RSVOptimization
    - cd "${CI_PROJECT_DIR}/${TEX_DIR}"
    - pdflatex -output-dir="${CI_PROJECT_DIR}/${TEX_OUTPUT_DIR}" RSVOptimization.tex
    - pdflatex -output-dir="${CI_PROJECT_DIR}/${TEX_OUTPUT_DIR}" RSVOptimization.tex
  artifacts:
    paths:
      - "${TEX_OUTPUT_DIR}/RSVOptimization.pdf"

# Set up docker image for the rest of the build, keyed off commit ID
.docker:
  tags: 
    - shell+private
    
docker.pre:
  extends: .docker
  stage: docker.pre
  script:
    - build/docker/pre build/default


# Turn digital ocean droplet on/off
digitalocean.pre:
  extends: .digitalocean.pre
  stage: digitalocean.pre

digitalocean.post:
  extends: .digitalocean.post
  stage: digitalocean.post

