stages:
  - tools
  - knitr
  - exports
  - pdf
  
variables:
  KNITR_OUTPUT_DIR: "knitr"
  OVERLEAF_ARTIFACTS_DIR: "overleaf"
  REVIEW_ARTIFACTS_DIR: rsv-optimization
  COMPOSE_FILES: --file docker-compose.yml --file docker-compose-gitlab.yml
  
.docker:
  tags:
      - docker
  services:
      - docker:18.09.7-dind
  variables:
      DOCKER_HOST: tcp://docker:2375/
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  image: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-compose-ci

tools:
  stage: tools
  extends: 
    - .docker
  script:
    - gitlab-docker-compose ${COMPOSE_FILES} --cache-from main paper-tools

knitr:
  stage: knitr
  extends: 
    - .docker
  tags:
    - docker-mem:3
  variables:
    KNITR_DRAFT_MODE: "FALSE"
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-knit
  cache:
    key: knitr
    paths:
      - cache
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-knitr"
    paths:
      - "${KNITR_OUTPUT_DIR}"

overleaf:
  extends: .docker
  stage: exports
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-overleaf
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-overleaf"
    paths:
      - "${OVERLEAF_ARTIFACTS_DIR}"

aap-pediatrics:
  extends: .docker
  stage: exports
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-figures
    - docker-compose ${COMPOSE_FILES} run paper-aap-pediatrics
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-overleaf"
    paths:
      - "${REVIEW_ARTIFACTS_DIR}"

pdf:
  stage: pdf
  extends: 
    - .docker
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper-pdf
    - mv "${OVERLEAF_ARTIFACTS_DIR}/RSVOptimization.pdf" .
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-pdf"
    paths:
      - "RSVOptimization.pdf"
