stages:
  - tools
  - journal
  
variables:
  COMPOSE_FILES: --file docker-compose.yml --file docker-compose-gitlab.yml
  
.docker:
  tags:
      - docker
  services:
      - docker:18.09.7-dind
  variables:
      DOCKER_HOST: tcp://docker:2375/
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  image: ${CI_REGISTRY}/ci-utilities/ci-commands/gitlab-docker-compose-ci

tools:
  stage: tools
  extends: 
    - .docker
  script:
    - gitlab-docker-compose ${COMPOSE_FILES} --cache-from main tools

nature-scirep:
  extends: .docker
  tags:
    - docker-mem:3
  stage: journal
  variables:
    KNITR_DRAFT_MODE: "FALSE"
  cache:
    key: knitr
    paths:
      - cache
  script:
    - docker login --username "${CI_REGISTRY_USER}" --password "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker-compose ${COMPOSE_FILES} run paper
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-nature-scirep"
    paths:
      - output
