# Helper for exporting for AAP pediatrics
# - Inlines bibliography
# - Renames images to match the text order
# - Rewrites a few other things to make conversion to RTF work

import re
import sys
import os
import shutil

# Inline the bibliography
tex = open(sys.argv[1]).read()
# tex = re.sub(r'\\bibliography\{(.*)\}', lambda f: open(f'{f.group(1)}.bbl').read(), tex)

# Get the figure names (in order) and rename the images
# Also pull out captions and labels to build list of figures and update references later
figRE = r'(?s)\\begin\{figure\}.*?\\end\{figure\}'
graphicRE = r'\\input\{\\figuresDir/(.*)\.tex\}'
captionRE = r'\\caption(?:\[(.*)\])?\{(.*)\}'
labelRE = r'\\label\{(.*)\}'

captions = []
labels = []

for figIdx, figM in enumerate(re.finditer(figRE, tex)):
	m = re.search(graphicRE, figM.group(0))
	shutil.copy(f'output/figures/{ m.group(1) }.pdf', f'output/figures/Fig{ figIdx + 1 }.pdf')
	captions.append(re.search(captionRE, figM.group(0)).group(2))
	labels.append(re.search(labelRE, figM.group(0)).group(1))

# Change preamble to RTF
tex = tex.replace(r'paper/preamble.tex', r'paper/preamble-rtf.tex')
# Drop graphics from figures
tex = re.sub(r'\\input\{\\figuresDir/(.*)\.tex\}', r'', tex)
# Delete knitr preamble
tex = re.sub(r'(?s)(\\documentclass[^\\]*)\\[^\n]*\n.*%%% end knitr preamble', r'\1\n', tex)
# Delete hangparas, it causes a weird RTF artifact
tex = re.sub(r'.*\{hangparas\}.*', r'', tex)

# Migrate figures to before appendix. This is basically a list of figures but generated by this script instead of latex
tex = re.sub(figRE, '', tex)
lof = '\n'.join(fr"\item \textbf{{Figure {idx + 1}: }}{caption}" for (idx, caption) in enumerate(captions))
lof = fr'''\section{{List of figures}}
\begin{{itemize}}
{ lof }
\end{{itemize}}
'''

tex = re.sub(r'(?s)(?=\\phantomsection.*\\addcontentsline\{toc\}\{section\}\{Bibliography\})', lambda m: lof, tex)

# Correct figure references
tex = re.sub(r'\\ref\{(fig:.*?)\}', lambda m: str(labels.index(m.group(1)) + 1), tex)

# Misc
tex = tex.replace(r'\raisebox{1pt}{\Circle}', r'\Circle')

open(sys.argv[1], 'w').write(tex)
